// iosApp/Package.swift
// Swift Package used to integrate the UniFFI-generated Swift bindings
// and the Rust XCFramework into the Xcode project.

// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "NodeXVPNPackage",
    platforms: [
        .iOS(.v16),
        .macOS(.v13),
    ],
    products: [
        .library(name: "NodexVpnCore", targets: ["NodexVpnCore"]),
        .library(name: "NodexVpnCoreFFI", targets: ["NodexVpnCoreFFI"]),
    ],
    targets: [
        // ── Pre-built XCFramework (Rust static lib) ────────────────────────
        .binaryTarget(
            name:  "NodexVpnCoreFFI",
            // Path relative to this Package.swift
            // The XCFramework is built by the CI pipeline:
            //   cargo build --release + lipo + xcodebuild -create-xcframework
            path: "../artifacts/NodexVpnCore.xcframework"
        ),

        // ── UniFFI-generated Swift wrapper ─────────────────────────────────
        .target(
            name: "NodexVpnCore",
            dependencies: ["NodexVpnCoreFFI"],
            // Sources generated by:
            //   cargo run --bin uniffi-bindgen generate src/nodex_vpn.udl --language swift
            path: "Sources/generated",
            publicHeadersPath: "."
        ),
    ]
)
