// shared/src/androidMain/kotlin/com/nodex/vpn/platform/PlatformVpnBridge.android.kt
package com.nodex.vpn.platform

import android.content.Context
import android.content.Intent
import android.net.VpnService
import com.nodex.vpn.manager.BootstrapStatus
import com.nodex.vpn.manager.RawVpnStats
import com.nodex.vpn.manager.RustVpnConfig
import kotlinx.coroutines.delay

// ── JNI bindings generated by UniFFI ─────────────────────────────────────────
external fun startNodex(
    socksListenAddr:         String,
    dnsListenAddr:           String,
    useBridges:              Boolean,
    bridgeLines:             Array<String>,
    strictExitNodes:         Boolean,
    preferredExitIso:        String?,
    circuitBuildTimeoutSecs: Int,
    stateDir:                String,
    cacheDir:                String,
)
external fun stopNodex()
external fun isRunning(): Boolean
external fun setExitNode(isoCode: String)
external fun getBootstrapPercent(): Int
external fun getBootstrapPhase(): String
external fun getBootstrapComplete(): Boolean
external fun getBytesSent(): Long
external fun getBytesReceived(): Long
external fun getSendRateBps(): Long
external fun getRecvRateBps(): Long
external fun getActiveCircuits(): Int
external fun getLatencyMs(): Double
external fun getCurrentExitCountry(): String
external fun getCurrentExitIp(): String
external fun getUptimeSecs(): Long

// ── Android actual implementation ─────────────────────────────────────────────

actual class PlatformVpnBridge actual constructor() {

    companion object {
        init {
            System.loadLibrary("nodex_vpn_core")
        }

        lateinit var applicationContext: Context
    }

    actual suspend fun prepare() {
        val intent = VpnService.prepare(applicationContext)
        if (intent != null) {
            throw IllegalStateException("VPN permission not granted. Show permission dialog first.")
        }
    }

    actual suspend fun startEngine(config: RustVpnConfig) {
        // Use Class.forName to avoid circular dependency between shared and androidApp modules
        val serviceClass = Class.forName("com.nodex.vpn.android.NodeXVpnService")
        val intent = Intent(applicationContext, serviceClass).apply {
            action = "com.nodex.vpn.START"
            putExtra("socks_addr",   config.socksListenAddr)
            putExtra("exit_iso",     config.preferredExitIso ?: "")
            putExtra("use_bridges",  config.useBridges)
            putExtra("strict_exit",  config.strictExitNodes)
        }
        applicationContext.startForegroundService(intent)

        startNodex(
            socksListenAddr         = config.socksListenAddr,
            dnsListenAddr           = config.dnsListenAddr,
            useBridges              = config.useBridges,
            bridgeLines             = config.bridgeLines.toTypedArray(),
            strictExitNodes         = config.strictExitNodes,
            preferredExitIso        = config.preferredExitIso,
            circuitBuildTimeoutSecs = config.circuitBuildTimeoutSecs.toInt(),
            stateDir                = stateDirectory(),
            cacheDir                = cacheDirectory(),
        )
    }

    actual suspend fun stopEngine() {
        stopNodex()
        val serviceClass = Class.forName("com.nodex.vpn.android.NodeXVpnService")
        applicationContext.startService(
            Intent(applicationContext, serviceClass).apply {
                action = "com.nodex.vpn.STOP"
            }
        )
    }

    actual suspend fun awaitBootstrap() {
        while (!getBootstrapComplete()) {
            delay(300)
        }
    }

    actual suspend fun setExitNode(isoCode: String) {
        setExitNode(isoCode)
    }

    actual fun getRealTimeStats() = RawVpnStats(
        bytesSent          = getBytesSent(),
        bytesReceived      = getBytesReceived(),
        sendRateBps        = getSendRateBps(),
        recvRateBps        = getRecvRateBps(),
        activeCircuits     = getActiveCircuits(),
        latencyMs          = getLatencyMs(),
        currentExitCountry = getCurrentExitCountry(),
        currentExitIp      = getCurrentExitIp(),
        uptimeSecs         = getUptimeSecs(),
    )

    actual fun getBootstrapStatus() = BootstrapStatus(
        percent      = getBootstrapPercent().toUByte(),
        phase        = getBootstrapPhase(),
        isComplete   = getBootstrapComplete(),
        errorMessage = null,
    )

    actual fun stateDirectory(): String =
        applicationContext.filesDir.resolve("nodex/state").also { it.mkdirs() }.absolutePath

    actual fun cacheDirectory(): String =
        applicationContext.cacheDir.resolve("nodex").also { it.mkdirs() }.absolutePath
}
