// iosApp/NodeXTunnel/PacketTunnelProvider.swift
//
// NodeX VPN – iOS/macOS Network Extension
//
// This extension process:
//   1. Receives configuration from the main app via NETunnelProviderProtocol.providerConfiguration
//   2. Calls the Rust core (via Swift bindings generated by UniFFI) to start arti
//   3. Sets up the virtual tun interface via Apple's packet tunnel APIs
//   4. Reads IP packets from the tunnel → forwards via arti SOCKS5
//   5. Handles IPC messages from the main app (SET_EXIT, GET_STATS, etc.)
//
// Required entitlements:
//   com.apple.developer.networking.networkextension: packet-tunnel-provider
//   com.apple.security.network.client
//   com.apple.security.network.server

import NetworkExtension
import os.log

// UniFFI-generated Swift module — produced by:
// cargo run --bin uniffi-bindgen generate src/nodex_vpn.udl --language swift
import NodexVpnCore

private let log = OSLog(subsystem: "com.nodex.vpn.ios.tunnel", category: "PacketTunnel")

class PacketTunnelProvider: NEPacketTunnelProvider {

    // ── State ──────────────────────────────────────────────────────────────
    private var statsTimer: Timer?
    private var running    = false

    // ── Lifecycle ──────────────────────────────────────────────────────────

    override func startTunnel(
        options: [String: NSObject]?,
        completionHandler: @escaping (Error?) -> Void
    ) {
        os_log("PacketTunnelProvider: startTunnel", log: log, type: .info)

        guard let cfg = self.protocolConfiguration as? NETunnelProviderProtocol,
              let pCfg = cfg.providerConfiguration else {
            completionHandler(TunnelError.missingConfig)
            return
        }

        // ── Parse configuration ────────────────────────────────────────────
        let socksAddr  = pCfg["socksAddr"]  as? String ?? "127.0.0.1:9050"
        let dnsAddr    = pCfg["dnsAddr"]    as? String ?? "127.0.0.1:5353"
        let useBridges = pCfg["useBridges"] as? Bool   ?? false
        let bridgesRaw = pCfg["bridges"]    as? String ?? ""
        let bridgeLines = bridgesRaw.isEmpty ? [] : bridgesRaw.components(separatedBy: "\n")
        let strictExit = pCfg["strictExit"] as? Bool   ?? true
        let exitIso    = pCfg["exitIso"]    as? String
        let timeout    = pCfg["timeout"]    as? Int32  ?? 30
        let stateDir   = pCfg["stateDir"]  as? String ?? NSTemporaryDirectory() + "nodex/state"
        let cacheDir   = pCfg["cacheDir"]  as? String ?? NSTemporaryDirectory() + "nodex/cache"

        // ── Create state/cache dirs ────────────────────────────────────────
        try? FileManager.default.createDirectory(atPath: stateDir,
            withIntermediateDirectories: true)
        try? FileManager.default.createDirectory(atPath: cacheDir,
            withIntermediateDirectories: true)

        // ── Start Rust/arti core ───────────────────────────────────────────
        do {
            let config = VpnConfig(
                socksListenAddr:          socksAddr,
                dnsListenAddr:            dnsAddr,
                useBridges:               useBridges,
                bridgeLines:              bridgeLines,
                strictExitNodes:          strictExit,
                preferredExitIso:         exitIso,
                circuitBuildTimeoutSecs:  UInt32(timeout),
                stateDir:                 stateDir,
                cacheDir:                 cacheDir
            )
            try startNodex(config: config)
            os_log("Rust core started", log: log, type: .info)
        } catch {
            os_log("Rust core start failed: %{public}@", log: log, type: .error, error.localizedDescription)
            completionHandler(error)
            return
        }

        // ── Configure Apple's virtual TUN interface ────────────────────────
        let tunnelSettings = buildTunnelSettings(tunAddr: "10.66.0.1", dnsAddr: "127.0.0.1")

        self.setTunnelNetworkSettings(tunnelSettings) { [weak self] error in
            guard let self = self else { return }
            if let error = error {
                os_log("setTunnelNetworkSettings error: %{public}@",
                       log: log, type: .error, error.localizedDescription)
                completionHandler(error)
                return
            }

            // ── Start packet relay loop ────────────────────────────────────
            self.running = true
            self.startPacketRelay()

            // ── Bootstrap poller ──────────────────────────────────────────
            self.pollBootstrapUntilComplete {
                os_log("Bootstrap complete", log: log, type: .info)
                completionHandler(nil)
            }
        }
    }

    override func stopTunnel(
        with reason: NEProviderStopReason,
        completionHandler: @escaping () -> Void
    ) {
        os_log("PacketTunnelProvider: stopTunnel (reason=%d)", log: log, type: .info, reason.rawValue)
        running = false
        statsTimer?.invalidate()

        do {
            try stopNodex()
        } catch {
            os_log("stopNodex error: %{public}@", log: log, type: .error, error.localizedDescription)
        }
        completionHandler()
    }

    // ── IPC from main app ──────────────────────────────────────────────────

    override func handleAppMessage(_ messageData: Data, completionHandler: ((Data?) -> Void)?) {
        guard let msg = String(data: messageData, encoding: .utf8) else { return }
        os_log("IPC message: %{public}@", log: log, type: .debug, msg)

        if msg.hasPrefix("SET_EXIT:") {
            let iso = String(msg.dropFirst("SET_EXIT:".count))
            try? setExitNode(isoCode: iso)
            completionHandler?(nil)

        } else if msg == "GET_STATS" {
            let stats = getRealTimeStats()
            let json  = encodeStats(stats)
            completionHandler?(json.data(using: .utf8))

        } else {
            completionHandler?(nil)
        }
    }

    // ── Packet relay loop ──────────────────────────────────────────────────

    private func startPacketRelay() {
        // Apple's PacketTunnelProvider gives us packetFlow to read/write raw IP packets.
        readPackets()
    }

    private func readPackets() {
        guard running else { return }
        packetFlow.readPacketObjects { [weak self] packets in
            guard let self = self, self.running else { return }
            for packet in packets {
                // Forward outbound IP packet to arti SOCKS5 proxy
                self.forwardToSocks(packet.data, proto: packet.protocolFamily)
            }
            // Recurse – Apple recommends re-calling readPacketObjects in its handler
            self.readPackets()
        }
    }

    private func forwardToSocks(_ data: Data, proto: NSNumber) {
        // Full implementation: parse IP header, extract dst IP+port,
        // open SOCKS5 connection through arti, relay data bidirectionally,
        // inject response packets back via packetFlow.writePacketObjects()
        //
        // For MVP this is handled by the Rust tun2socks layer which receives
        // the TUN fd via protectSocket/setTunFd (exposed by UniFFI).
    }

    // ── Bootstrap polling ──────────────────────────────────────────────────

    private func pollBootstrapUntilComplete(completion: @escaping () -> Void) {
        var attempts = 0
        Timer.scheduledTimer(withTimeInterval: 0.4, repeats: true) { timer in
            attempts += 1
            let bs = getBootstrapStatus()
            os_log("Bootstrap: %d%% – %{public}@",
                   log: log, type: .debug, bs.percent, bs.phase)
            if bs.isComplete {
                timer.invalidate()
                completion()
            } else if attempts > 300 {
                timer.invalidate()
                os_log("Bootstrap timeout", log: log, type: .error)
                completion() // proceed anyway
            }
        }
    }

    // ── Network settings builder ───────────────────────────────────────────

    private func buildTunnelSettings(tunAddr: String, dnsAddr: String) -> NEPacketTunnelNetworkSettings {
        let settings           = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "127.0.0.1")
        settings.mtu           = 1500

        // IPv4
        let ipv4               = NEIPv4Settings(addresses: [tunAddr], subnetMasks: ["255.255.255.0"])
        ipv4.includedRoutes    = [NEIPv4Route.default()]
        settings.ipv4Settings  = ipv4

        // IPv6
        let ipv6               = NEIPv6Settings(addresses: ["fd00::1"], networkPrefixLengths: [64])
        ipv6.includedRoutes    = [NEIPv6Route.default()]
        settings.ipv6Settings  = ipv6

        // DNS – route to our DoT listener
        let dns                = NEDNSSettings(servers: [dnsAddr])
        dns.matchDomains       = [""]  // Match all domains
        settings.dnsSettings   = dns

        return settings
    }

    // ── Stats encoder ──────────────────────────────────────────────────────

    private func encodeStats(_ s: VpnStats) -> String {
        return """
        {"bytesSent":\(s.bytesSent),"bytesReceived":\(s.bytesReceived),\
        "sendRateBps":\(s.sendRateBps),"recvRateBps":\(s.recvRateBps),\
        "latencyMs":\(s.latencyMs),"exitCountry":"\(s.currentExitCountry)",\
        "exitIp":"\(s.currentExitIp)","uptime":\(s.uptimeSecs)}
        """
    }
}

// ── Errors ────────────────────────────────────────────────────────────────────

enum TunnelError: Error, LocalizedError {
    case missingConfig

    var errorDescription: String? {
        switch self {
        case .missingConfig: return "Missing VPN provider configuration"
        }
    }
}
