// tvosApp/tvosApp/ContentView.swift
import SwiftUI
import shared   // KMP shared framework

/// Root SwiftUI view for Apple TV — hosts the Compose Multiplatform UI.
struct ContentView: View {
    var body: some View {
        TvComposeView()
            .ignoresSafeArea()   // tvOS: no safe-area insets needed
            .edgesIgnoringSafeArea(.all)
    }
}

// ── KMP Compose ↔ SwiftUI bridge ─────────────────────────────────────────────
struct TvComposeView: UIViewControllerRepresentable {

    func makeUIViewController(context: Context) -> UIViewController {
        // TvMainViewControllerKt is generated by KMP from TvMainViewController.kt
        return TvMainViewControllerKt.TvMainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
