// iosApp/iosApp/ContentView.swift
import SwiftUI
import shared   // KMP shared framework

/// Root SwiftUI view — hosts the Compose Multiplatform UI via UIViewControllerRepresentable.
struct ContentView: View {
    var body: some View {
        ComposeView()
            .ignoresSafeArea(.keyboard)          // Compose handles keyboard insets
            .ignoresSafeArea(.container, edges: .bottom)
    }
}

// ── Compose ↔ SwiftUI bridge ──────────────────────────────────────────────────

struct ComposeView: UIViewControllerRepresentable {

    func makeUIViewController(context: Context) -> UIViewController {
        // MainViewControllerKt is generated by the KMP Compose framework
        // It instantiates the shared `NodeXApp` composable
        return MainViewControllerKt.MainViewController()
    }

    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {}
}
